# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userInterface.ui'
#
# Created: Sun Jun 28 19:36:19 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MatrixToHex(object):
    def setupUi(self, MatrixToHex):
        MatrixToHex.setObjectName(_fromUtf8("MatrixToHex"))
        MatrixToHex.resize(233, 247)
        self.ha = QtGui.QPushButton(MatrixToHex)
        self.ha.setGeometry(QtCore.QRect(30, 20, 21, 21))
        self.ha.setText(_fromUtf8(""))
        self.ha.setObjectName(_fromUtf8("ha"))
        self.ga = QtGui.QPushButton(MatrixToHex)
        self.ga.setGeometry(QtCore.QRect(30, 40, 21, 21))
        self.ga.setText(_fromUtf8(""))
        self.ga.setObjectName(_fromUtf8("ga"))
        self.fa = QtGui.QPushButton(MatrixToHex)
        self.fa.setGeometry(QtCore.QRect(30, 60, 21, 21))
        self.fa.setText(_fromUtf8(""))
        self.fa.setObjectName(_fromUtf8("fa"))
        self.ea = QtGui.QPushButton(MatrixToHex)
        self.ea.setGeometry(QtCore.QRect(30, 80, 21, 21))
        self.ea.setText(_fromUtf8(""))
        self.ea.setObjectName(_fromUtf8("ea"))
        self.ca = QtGui.QPushButton(MatrixToHex)
        self.ca.setGeometry(QtCore.QRect(30, 120, 21, 21))
        self.ca.setText(_fromUtf8(""))
        self.ca.setObjectName(_fromUtf8("ca"))
        self.da = QtGui.QPushButton(MatrixToHex)
        self.da.setGeometry(QtCore.QRect(30, 100, 21, 21))
        self.da.setText(_fromUtf8(""))
        self.da.setObjectName(_fromUtf8("da"))
        self.ba = QtGui.QPushButton(MatrixToHex)
        self.ba.setGeometry(QtCore.QRect(30, 140, 21, 21))
        self.ba.setText(_fromUtf8(""))
        self.ba.setObjectName(_fromUtf8("ba"))
        self.aa = QtGui.QPushButton(MatrixToHex)
        self.aa.setGeometry(QtCore.QRect(30, 160, 21, 21))
        self.aa.setText(_fromUtf8(""))
        self.aa.setObjectName(_fromUtf8("aa"))
        self.gb = QtGui.QPushButton(MatrixToHex)
        self.gb.setGeometry(QtCore.QRect(50, 40, 21, 21))
        self.gb.setText(_fromUtf8(""))
        self.gb.setObjectName(_fromUtf8("gb"))
        self.hb = QtGui.QPushButton(MatrixToHex)
        self.hb.setGeometry(QtCore.QRect(50, 20, 21, 21))
        self.hb.setText(_fromUtf8(""))
        self.hb.setObjectName(_fromUtf8("hb"))
        self.fb = QtGui.QPushButton(MatrixToHex)
        self.fb.setGeometry(QtCore.QRect(50, 60, 21, 21))
        self.fb.setText(_fromUtf8(""))
        self.fb.setObjectName(_fromUtf8("fb"))
        self.ab = QtGui.QPushButton(MatrixToHex)
        self.ab.setGeometry(QtCore.QRect(50, 160, 21, 21))
        self.ab.setText(_fromUtf8(""))
        self.ab.setObjectName(_fromUtf8("ab"))
        self.cb = QtGui.QPushButton(MatrixToHex)
        self.cb.setGeometry(QtCore.QRect(50, 120, 21, 21))
        self.cb.setText(_fromUtf8(""))
        self.cb.setObjectName(_fromUtf8("cb"))
        self.bb = QtGui.QPushButton(MatrixToHex)
        self.bb.setGeometry(QtCore.QRect(50, 140, 21, 21))
        self.bb.setText(_fromUtf8(""))
        self.bb.setObjectName(_fromUtf8("bb"))
        self.db = QtGui.QPushButton(MatrixToHex)
        self.db.setGeometry(QtCore.QRect(50, 100, 21, 21))
        self.db.setText(_fromUtf8(""))
        self.db.setObjectName(_fromUtf8("db"))
        self.eb = QtGui.QPushButton(MatrixToHex)
        self.eb.setGeometry(QtCore.QRect(50, 80, 21, 21))
        self.eb.setText(_fromUtf8(""))
        self.eb.setObjectName(_fromUtf8("eb"))
        self.cd = QtGui.QPushButton(MatrixToHex)
        self.cd.setGeometry(QtCore.QRect(90, 120, 21, 21))
        self.cd.setText(_fromUtf8(""))
        self.cd.setObjectName(_fromUtf8("cd"))
        self.gc = QtGui.QPushButton(MatrixToHex)
        self.gc.setGeometry(QtCore.QRect(70, 40, 21, 21))
        self.gc.setText(_fromUtf8(""))
        self.gc.setObjectName(_fromUtf8("gc"))
        self.hc = QtGui.QPushButton(MatrixToHex)
        self.hc.setGeometry(QtCore.QRect(70, 20, 21, 21))
        self.hc.setText(_fromUtf8(""))
        self.hc.setObjectName(_fromUtf8("hc"))
        self.ad = QtGui.QPushButton(MatrixToHex)
        self.ad.setGeometry(QtCore.QRect(90, 160, 21, 21))
        self.ad.setText(_fromUtf8(""))
        self.ad.setObjectName(_fromUtf8("ad"))
        self.dd = QtGui.QPushButton(MatrixToHex)
        self.dd.setGeometry(QtCore.QRect(90, 100, 21, 21))
        self.dd.setText(_fromUtf8(""))
        self.dd.setObjectName(_fromUtf8("dd"))
        self.hd = QtGui.QPushButton(MatrixToHex)
        self.hd.setGeometry(QtCore.QRect(90, 20, 21, 21))
        self.hd.setText(_fromUtf8(""))
        self.hd.setObjectName(_fromUtf8("hd"))
        self.bd = QtGui.QPushButton(MatrixToHex)
        self.bd.setGeometry(QtCore.QRect(90, 140, 21, 21))
        self.bd.setText(_fromUtf8(""))
        self.bd.setObjectName(_fromUtf8("bd"))
        self.fc = QtGui.QPushButton(MatrixToHex)
        self.fc.setGeometry(QtCore.QRect(70, 60, 21, 21))
        self.fc.setText(_fromUtf8(""))
        self.fc.setObjectName(_fromUtf8("fc"))
        self.cc = QtGui.QPushButton(MatrixToHex)
        self.cc.setGeometry(QtCore.QRect(70, 120, 21, 21))
        self.cc.setText(_fromUtf8(""))
        self.cc.setObjectName(_fromUtf8("cc"))
        self.ac = QtGui.QPushButton(MatrixToHex)
        self.ac.setGeometry(QtCore.QRect(70, 160, 21, 21))
        self.ac.setText(_fromUtf8(""))
        self.ac.setObjectName(_fromUtf8("ac"))
        self.bc = QtGui.QPushButton(MatrixToHex)
        self.bc.setGeometry(QtCore.QRect(70, 140, 21, 21))
        self.bc.setText(_fromUtf8(""))
        self.bc.setObjectName(_fromUtf8("bc"))
        self.gd = QtGui.QPushButton(MatrixToHex)
        self.gd.setGeometry(QtCore.QRect(90, 40, 21, 21))
        self.gd.setText(_fromUtf8(""))
        self.gd.setObjectName(_fromUtf8("gd"))
        self.fd = QtGui.QPushButton(MatrixToHex)
        self.fd.setGeometry(QtCore.QRect(90, 60, 21, 21))
        self.fd.setText(_fromUtf8(""))
        self.fd.setObjectName(_fromUtf8("fd"))
        self.ed = QtGui.QPushButton(MatrixToHex)
        self.ed.setGeometry(QtCore.QRect(90, 80, 21, 21))
        self.ed.setText(_fromUtf8(""))
        self.ed.setObjectName(_fromUtf8("ed"))
        self.dc = QtGui.QPushButton(MatrixToHex)
        self.dc.setGeometry(QtCore.QRect(70, 100, 21, 21))
        self.dc.setText(_fromUtf8(""))
        self.dc.setObjectName(_fromUtf8("dc"))
        self.ec = QtGui.QPushButton(MatrixToHex)
        self.ec.setGeometry(QtCore.QRect(70, 80, 21, 21))
        self.ec.setText(_fromUtf8(""))
        self.ec.setObjectName(_fromUtf8("ec"))
        self.fe = QtGui.QPushButton(MatrixToHex)
        self.fe.setGeometry(QtCore.QRect(110, 60, 21, 21))
        self.fe.setText(_fromUtf8(""))
        self.fe.setObjectName(_fromUtf8("fe"))
        self.eh = QtGui.QPushButton(MatrixToHex)
        self.eh.setGeometry(QtCore.QRect(170, 80, 21, 21))
        self.eh.setText(_fromUtf8(""))
        self.eh.setObjectName(_fromUtf8("eh"))
        self.ch = QtGui.QPushButton(MatrixToHex)
        self.ch.setGeometry(QtCore.QRect(170, 120, 21, 21))
        self.ch.setText(_fromUtf8(""))
        self.ch.setObjectName(_fromUtf8("ch"))
        self.bh = QtGui.QPushButton(MatrixToHex)
        self.bh.setGeometry(QtCore.QRect(170, 140, 21, 21))
        self.bh.setText(_fromUtf8(""))
        self.bh.setObjectName(_fromUtf8("bh"))
        self.ef = QtGui.QPushButton(MatrixToHex)
        self.ef.setGeometry(QtCore.QRect(130, 80, 21, 21))
        self.ef.setText(_fromUtf8(""))
        self.ef.setObjectName(_fromUtf8("ef"))
        self.cg = QtGui.QPushButton(MatrixToHex)
        self.cg.setGeometry(QtCore.QRect(150, 120, 21, 21))
        self.cg.setText(_fromUtf8(""))
        self.cg.setObjectName(_fromUtf8("cg"))
        self.df = QtGui.QPushButton(MatrixToHex)
        self.df.setGeometry(QtCore.QRect(130, 100, 21, 21))
        self.df.setText(_fromUtf8(""))
        self.df.setObjectName(_fromUtf8("df"))
        self.ff = QtGui.QPushButton(MatrixToHex)
        self.ff.setGeometry(QtCore.QRect(130, 60, 21, 21))
        self.ff.setText(_fromUtf8(""))
        self.ff.setObjectName(_fromUtf8("ff"))
        self.de = QtGui.QPushButton(MatrixToHex)
        self.de.setGeometry(QtCore.QRect(110, 100, 21, 21))
        self.de.setText(_fromUtf8(""))
        self.de.setObjectName(_fromUtf8("de"))
        self.fh = QtGui.QPushButton(MatrixToHex)
        self.fh.setGeometry(QtCore.QRect(170, 60, 21, 21))
        self.fh.setText(_fromUtf8(""))
        self.fh.setObjectName(_fromUtf8("fh"))
        self.fg = QtGui.QPushButton(MatrixToHex)
        self.fg.setGeometry(QtCore.QRect(150, 60, 21, 21))
        self.fg.setText(_fromUtf8(""))
        self.fg.setObjectName(_fromUtf8("fg"))
        self.hf = QtGui.QPushButton(MatrixToHex)
        self.hf.setGeometry(QtCore.QRect(130, 20, 21, 21))
        self.hf.setText(_fromUtf8(""))
        self.hf.setObjectName(_fromUtf8("hf"))
        self.hh = QtGui.QPushButton(MatrixToHex)
        self.hh.setGeometry(QtCore.QRect(170, 20, 21, 21))
        self.hh.setText(_fromUtf8(""))
        self.hh.setObjectName(_fromUtf8("hh"))
        self.cf = QtGui.QPushButton(MatrixToHex)
        self.cf.setGeometry(QtCore.QRect(130, 120, 21, 21))
        self.cf.setText(_fromUtf8(""))
        self.cf.setObjectName(_fromUtf8("cf"))
        self.eg = QtGui.QPushButton(MatrixToHex)
        self.eg.setGeometry(QtCore.QRect(150, 80, 21, 21))
        self.eg.setText(_fromUtf8(""))
        self.eg.setObjectName(_fromUtf8("eg"))
        self.be = QtGui.QPushButton(MatrixToHex)
        self.be.setGeometry(QtCore.QRect(110, 140, 21, 21))
        self.be.setText(_fromUtf8(""))
        self.be.setObjectName(_fromUtf8("be"))
        self.ee = QtGui.QPushButton(MatrixToHex)
        self.ee.setGeometry(QtCore.QRect(110, 80, 21, 21))
        self.ee.setText(_fromUtf8(""))
        self.ee.setObjectName(_fromUtf8("ee"))
        self.dh = QtGui.QPushButton(MatrixToHex)
        self.dh.setGeometry(QtCore.QRect(170, 100, 21, 21))
        self.dh.setText(_fromUtf8(""))
        self.dh.setObjectName(_fromUtf8("dh"))
        self.dg = QtGui.QPushButton(MatrixToHex)
        self.dg.setGeometry(QtCore.QRect(150, 100, 21, 21))
        self.dg.setText(_fromUtf8(""))
        self.dg.setObjectName(_fromUtf8("dg"))
        self.ge = QtGui.QPushButton(MatrixToHex)
        self.ge.setGeometry(QtCore.QRect(110, 40, 21, 21))
        self.ge.setText(_fromUtf8(""))
        self.ge.setObjectName(_fromUtf8("ge"))
        self.ae = QtGui.QPushButton(MatrixToHex)
        self.ae.setGeometry(QtCore.QRect(110, 160, 21, 21))
        self.ae.setText(_fromUtf8(""))
        self.ae.setObjectName(_fromUtf8("ae"))
        self.hg = QtGui.QPushButton(MatrixToHex)
        self.hg.setGeometry(QtCore.QRect(150, 20, 21, 21))
        self.hg.setText(_fromUtf8(""))
        self.hg.setObjectName(_fromUtf8("hg"))
        self.he = QtGui.QPushButton(MatrixToHex)
        self.he.setGeometry(QtCore.QRect(110, 20, 21, 21))
        self.he.setText(_fromUtf8(""))
        self.he.setObjectName(_fromUtf8("he"))
        self.ce = QtGui.QPushButton(MatrixToHex)
        self.ce.setGeometry(QtCore.QRect(110, 120, 21, 21))
        self.ce.setText(_fromUtf8(""))
        self.ce.setObjectName(_fromUtf8("ce"))
        self.ag = QtGui.QPushButton(MatrixToHex)
        self.ag.setGeometry(QtCore.QRect(150, 160, 21, 21))
        self.ag.setText(_fromUtf8(""))
        self.ag.setObjectName(_fromUtf8("ag"))
        self.gh = QtGui.QPushButton(MatrixToHex)
        self.gh.setGeometry(QtCore.QRect(170, 40, 21, 21))
        self.gh.setText(_fromUtf8(""))
        self.gh.setObjectName(_fromUtf8("gh"))
        self.bg = QtGui.QPushButton(MatrixToHex)
        self.bg.setGeometry(QtCore.QRect(150, 140, 21, 21))
        self.bg.setText(_fromUtf8(""))
        self.bg.setObjectName(_fromUtf8("bg"))
        self.ah = QtGui.QPushButton(MatrixToHex)
        self.ah.setGeometry(QtCore.QRect(170, 160, 21, 21))
        self.ah.setText(_fromUtf8(""))
        self.ah.setObjectName(_fromUtf8("ah"))
        self.gg = QtGui.QPushButton(MatrixToHex)
        self.gg.setGeometry(QtCore.QRect(150, 40, 21, 21))
        self.gg.setText(_fromUtf8(""))
        self.gg.setObjectName(_fromUtf8("gg"))
        self.bf = QtGui.QPushButton(MatrixToHex)
        self.bf.setGeometry(QtCore.QRect(130, 140, 21, 21))
        self.bf.setText(_fromUtf8(""))
        self.bf.setObjectName(_fromUtf8("bf"))
        self.gf = QtGui.QPushButton(MatrixToHex)
        self.gf.setGeometry(QtCore.QRect(130, 40, 21, 21))
        self.gf.setText(_fromUtf8(""))
        self.gf.setObjectName(_fromUtf8("gf"))
        self.af = QtGui.QPushButton(MatrixToHex)
        self.af.setGeometry(QtCore.QRect(130, 160, 21, 21))
        self.af.setText(_fromUtf8(""))
        self.af.setObjectName(_fromUtf8("af"))
        self.screen = QtGui.QLineEdit(MatrixToHex)
        self.screen.setGeometry(QtCore.QRect(0, 210, 231, 20))
        self.screen.setObjectName(_fromUtf8("screen"))

        self.retranslateUi(MatrixToHex)
        QtCore.QMetaObject.connectSlotsByName(MatrixToHex)

    def retranslateUi(self, MatrixToHex):
        MatrixToHex.setWindowTitle(_translate("MatrixToHex", "8x8 Matrix", None))
        self.screen.setPlaceholderText(_translate("MatrixToHex", "0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ", None))

